applicationsets:

  platform-infra:
    namespace: argocd
    goTemplate: true
    generators:
      - git:
          repoURL: "https://gitlab.com/from-the-lamp/infra/argo-apps.git"
          revision: HEAD
          directories:
            - path: 'infra/platform/*'
    ignoreApplicationDifferences:
      - jsonPointers:
          - /spec/syncPolicy
    template:
      metadata:
        name: "infra-{{.path.basename}}"
        annotations:
          notifications.argoproj.io/subscribe.on-sync-succeeded.slack: 'argocd-platform'
      spec:
        project: platform-infra
        source:
          repoURL: "https://gitlab.com/from-the-lamp/infra/argo-apps.git"
          targetRevision: HEAD
          path: "{{.path.path}}"
          helm:
            releaseName: "{{.path.basename}}"
        destination:
          name: infra
          namespace: "{{.path.basename}}"
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true
        ignoreDifferences:
          - group: admissionregistration.k8s.io
            kind: ValidatingWebhookConfiguration
            jsonPointers:
              - /webhooks/0/failurePolicy
          - group: postgresql.cnpg.io
            kind: Cluster
            name: postgres
            namespace: postgres
            jqPathExpressions:
              - .spec.managed.roles[].passwordSecret.remoteSecretKey
          - group: ""
            kind: Service
            jsonPointers:
              - /spec/externalName
              
  product-infra:
    namespace: argocd
    goTemplate: true
    generators:
      - git:
          repoURL: "https://gitlab.com/from-the-lamp/infra/argo-apps.git"
          revision: HEAD
          directories:
            - path: 'infra/product/*'
    ignoreApplicationDifferences:
      - jsonPointers:
          - /spec/syncPolicy
    template:
      metadata:
        name: "infra-{{.path.basename}}"
        annotations:
          notifications.argoproj.io/subscribe.on-sync-succeeded.slack: 'argocd-product'
      spec:
        project: product-infra
        source:
          repoURL: "https://gitlab.com/from-the-lamp/infra/argo-apps.git"
          targetRevision: HEAD
          path: "{{.path.path}}"
          helm:
            releaseName: "{{.path.basename}}"
        destination:
          name: infra
          namespace: "product"
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true

  platform-prod-0:
    namespace: argocd
    goTemplate: true
    generators:
      - git:
          repoURL: "https://gitlab.com/from-the-lamp/infra/argo-apps.git"
          revision: HEAD
          directories:
            - path: 'prod-0/platform/*'
    ignoreApplicationDifferences:
      - jsonPointers:
          - /spec/syncPolicy
    template:
      metadata:
        name: "prod-0-{{.path.basename}}"
        annotations:
          notifications.argoproj.io/subscribe.on-sync-succeeded.slack: 'argocd-platform'
      spec:
        project: platform-prod
        source:
          repoURL: "https://gitlab.com/from-the-lamp/infra/argo-apps.git"
          targetRevision: HEAD
          path: "{{.path.path}}"
          helm:
            releaseName: "{{.path.basename}}"
        destination:
          name: prod-0
          namespace: "{{.path.basename}}"
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true
        ignoreDifferences:
          - group: admissionregistration.k8s.io
            kind: ValidatingWebhookConfiguration
            jsonPointers:
              - /webhooks/0/failurePolicy
          - group: postgresql.cnpg.io
            kind: Cluster
            name: postgres
            namespace: postgres
            jqPathExpressions:
              - .spec.managed.roles[].passwordSecret.remoteSecretKey
          - group: ""
            kind: Service
            jsonPointers:
              - /spec/externalName

  product-prod-0:
    namespace: argocd
    goTemplate: true
    generators:
      - git:
          repoURL: "https://gitlab.com/from-the-lamp/infra/argo-apps.git"
          revision: HEAD
          directories:
            - path: 'prod-0/product/*'
    ignoreApplicationDifferences:
      - jsonPointers:
          - /spec/syncPolicy
    template:
      metadata:
        name: "prod-0-{{.path.basename}}"
        annotations:
          argocd-image-updater.argoproj.io/git-branch: main
          argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-git-creds
          argocd-image-updater.argoproj.io/image-list: app=registry.gitlab.com/from-the-lamp/frontend/{{.path.basename}}:latest
          argocd-image-updater.argoproj.io/app.force-update: "true"
          argocd-image-updater.argoproj.io/app.update-strategy: digest
          argocd-image-updater.argoproj.io/app.helm.image-name: image.name
          argocd-image-updater.argoproj.io/app.helm.image-tag: image.tag
          notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd-product
      spec:
        project: product-prod
        source:
          repoURL: "https://gitlab.com/from-the-lamp/infra/argo-apps.git"
          targetRevision: HEAD
          path: "{{.path.path}}"
          helm:
            releaseName: "{{.path.basename}}"
        destination:
          name: prod-0
          namespace: "product"
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true