apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: OriginIssuer
metadata:
  name: origin-ca-issuer
  namespace: {{ .Release.Namespace }}
spec:
  requestType: OriginECC
  auth:
    serviceKeyRef:
      name: origin-ca-issuer-service-key
      key: key
