#!/usr/bin/env bash

GITLAB_CI_FILE=".gitlab-ci.yml"
LIST=$(find -name terragrunt.hcl)

echo "#This file was generated by $(basename $BASH_SOURCE), please do not modify manually
include:
  - project: "from-the-lamp/infra/ci-cd-includes"
    file: "functions/terraform.yml"
" > $GITLAB_CI_FILE

for LINE in $LIST; do
    LINE=$(echo $LINE | cut -c3- | sed 's/\/terragrunt.hcl//g')
    echo "1:${LINE}:
  extends: .plan
  variables:
    DIR: ${LINE}
    $(if [[ $LINE == *"prod"* ]]; then 
    echo "AWS_PROFILE: lamp-prod"
    elif [[ $LINE == *"dev"* ]]; then
    echo "AWS_PROFILE: lamp-dev"
    else
    echo "AWS_PROFILE: fixme"
    fi)
2:${LINE}:
  extends: .apply
  variables:
    DIR: ${LINE}
    AWS_PROFILE: lamp-prod
">> $GITLAB_CI_FILE
done
