version: "3"

dotenv: [".env"]
env:
  LOG_LEVEL: info
  OCI_CONFIG_PATH: "{{.HOME}}/.oci/config"
   
silent: true
tasks:

  default:
    desc: List all available tasks
    cmd: task --list-all

  cleanup:
    desc: Remove temporary files
    cmds:
    - find . -type d -name ".terragrunt-cache" -prune -exec rm -rf {} \;
    - find . -type d -name ".terraform" -prune -exec rm -rf {} \;
    - find . -iname "*generated*" -delete;
    - find . -iname ".helmignore" -delete;
    - find . -iname ".terraform.lock.hcl" -delete;

  fmt:
    desc: Format all HCL code
    cmds:
    - terragrunt hcl format

  .terragrunt:
    internal: true
    dir: $DIR
    cmds:
    - |
      terragrunt {{ .ACTION }} \
        -compact-warnings --non-interactive  \
        --log-level {{.LOG_LEVEL}} \
        {{.CLI_ARGS}} {{ .ADDITION_ARGS }}

  plan:
    desc: Run plan in the specified DIR (set DIR=...)
    cmds:
    - task: .terragrunt
      vars: {
        ACTION: "plan",
      }

  apply:
    desc: Run apply in the specified DIR (set DIR=...)
    cmds:
    - task: .terragrunt
      vars: {
        ACTION: "apply",
      }

  destroy:
    desc: Run destroy in the specified DIR (set DIR=...)
    cmds:
    - task: .terragrunt
      vars: {
        ACTION: "destroy",
      }
      
  validate:
    desc: Run validate in the specified DIR (set DIR=...)
    cmds:
    - task: .terragrunt
      vars: {
        ACTION: "validate",
      }

  plan:all:
    desc: Run plan for all modules in subdirectories of DIR (set DIR=...)
    cmds:
    - task: .terragrunt
      vars: {
        ACTION: "plan --all",
      }

  apply:all:
    desc: Run apply for all modules in subdirectories of DIR (set DIR=...)
    cmds:
    - task: .terragrunt
      vars: {
        ACTION: "apply --all",
      }

  outputs:
    desc: Show module outputs
    cmds:
    - task: .terragrunt
      vars: {
        ACTION: "output --all",
      }

  unlock:
    desc: Unlock state by ID
    cmds:
    - task: .terragrunt
      vars: {
        ACTION: "force-unlock {{.CLI_ARGS}}",
      }
