version: "3"

dotenv: [".env"]

env:
  DEFAULT_REGION: eu-frankfurt-1
  
silent: true
tasks:
  rm:all:
    cmds:
      - find . -type d -name ".terragrunt-cache" -prune -exec rm -rf {} \;
      - find . -type d -name ".terraform" -prune -exec rm -rf {} \;
      - find . -iname "*generated*" -delete;
      - find . -iname ".terraform.lock.hcl" -delete;
      - find . -iname ".helmignore" -delete;
  terragrunt:
    dir: $DIR
    cmds:
      - task: rm:all
      -
        terragrunt {{ .ACTION }}
        $(if [ "{{.AUTO_APPROVE}}" == "true" ]; then echo "-auto-approve"; fi)
        $(if [ "{{.NON_INTERACTIVE}}" == "true" ]; then echo "--terragrunt-non-interactive"; fi)

  plan:
    cmds:
      - task: terragrunt
        vars: {
          ACTION: "plan",
          NON_INTERACTIVE: "true",
        }
  plan:all:
    cmds:
      - task: terragrunt
        vars: {
          ACTION: "run-all plan",
          NON_INTERACTIVE: "true",
        }

  apply:
    cmds:
      - task: terragrunt
        vars: {
          ACTION: "apply",
        }
  apply:force:
    cmds:
      - task: terragrunt
        vars: {
          ACTION: "apply",
          NON_INTERACTIVE: "true",
          AUTO_APPROVE: "true"
        }
  apply:all:
    cmds:
      - task: terragrunt
        vars: {
          ACTION: "run-all apply",
        }
  apply:all:force:
    cmds:
      - task: terragrunt
        vars: {
          ACTION: "run-all apply",
          NON_INTERACTIVE: "true",
          AUTO_APPROVE: "true"
        }

  destroy:
    cmds:
      - task: terragrunt
        vars: {
          ACTION: "destroy",
        }
  destroy:force:
    cmds:
      - task: terragrunt
        vars: {
          ACTION: "destroy",
          NON_INTERACTIVE: "true",
          AUTO_APPROVE: "true"
        }
  destroy:all:
    cmds:
      - task: terragrunt
        vars: {
          ACTION: "run-all destroy",
        }
  destroy:all:force:
    cmds:
      - task: terragrunt
        vars: {
          ACTION: "run-all destroy",
          NON_INTERACTIVE: "true",
          AUTO_APPROVE: "true"
        }

  unlock:
    dir: $DIR
    cmds:
      - task: rm
      - terragrunt force-unlock $ID
