version: "3"

dotenv: [".env"]
env:
  OCI_CONFIG_PATH: "{{.HOME}}/.oci/config"

silent: true
tasks:
  cleanup:
    cmds:
    - find . -type d -name ".terragrunt-cache" -prune -exec rm -rf {} \;
    - find . -type d -name ".terraform" -prune -exec rm -rf {} \;
    - find . -iname "*generated*" -delete;
    - find . -iname ".terraform.lock.hcl" -delete;
    - find . -iname ".helmignore" -delete;

  terragrunt:
    dir: $DIR
    cmds:
    - terragrunt run-all {{ .ACTION }} --terragrunt-non-interactive {{ .CLI_ARGS }}

  plan:
    cmds:
    - task: terragrunt
      vars: {
        ACTION: "plan",
      }
  apply:
    cmds:
    - task: terragrunt
      vars: {
        ACTION: "apply",
      }
  destroy:
    cmds:
    - task: terragrunt
      vars: {
        ACTION: "destroy",
      }
  validate:
    cmds:
    - task: terragrunt
      vars: {
        ACTION: "validate",
      }
  output:
    cmds:
    - task: terragrunt
      vars: {
        ACTION: "output",
      }
      
  unlock:
    dir: $DIR
    cmds:
    - terragrunt force-unlock {{.CLI_ARGS}}

  fmt:
    cmds:
    - terragrunt hclfmt
