prometheus:  
  url: "http://kube-prometheus-stack-prometheus.monitoring:9090"

grafana:
  in_cluster_url: "http://kube-prometheus-stack-grafana.monitoring:80"

api:
  namespaces:
    exclude:
    - "^istio-operator"
    - "^kube-.*"
    - "^openshift.*"
    - "^ibm.*"
    - "^kiali-operator"
    - "monitoring"
    - "infra"
    - "longhorn-system"

deployment:
  accessible_namespaces:
  - "**"
