grafana:
  enabled: true
  grafana.ini:
    server:
      root_url: https://grafana.from-the-lamp.com
    users:
      auto_assign_org_role: Editor
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  plugins:
    - hamedkarbasi93-kafka-datasource
    - redis-datasource
    - grafana-piechart-panel
    - yesoreyeram-boomtable-panel
  dashboards:
    default:
      Istio-Mesh:
        gnetId: 7639
        revision: 149
        datasource: Prometheus

gateway:
  enabled: true
  external: true
  hosts:
  - grafana.from-the-lamp.com
destination:
  name: kube-prometheus-stack-grafana
  port: 80

defaultRules:
  create: true
  rules:
    alertmanager: false
    etcd: false
    configReloaders: true
    general: true
    k8s: true
    kubeApiserverAvailability: true
    kubeApiserverBurnrate: true
    kubeApiserverHistogram: true
    kubeApiserverSlos: true
    kubelet: true
    kubeProxy: false
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    kubeScheduler: true
    kubeStateMetrics: true
    network: true
    node: true
    nodeExporterAlerting: true
    nodeExporterRecording: true
    prometheus: true
    prometheusOperator: true

alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: 'istiod'
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - istio-system
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: istiod;http-monitoring
    - job_name: 'envoy-stats'
      metrics_path: /stats/prometheus
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_container_port_name]
        action: keep
        regex: '.*-envoy-prom'
