apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
stringData:
  privateKey: |
    {{- .Values.oracle.vault.privateKey | b64dec | nindent 4 }}
  fingerprint: {{ .Values.oracle.vault.fingerprint | quote }}
