kind: DaemonSet
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: NotIn
              values:
                - "true"

service:
  externalTrafficPolicy: Local
  annotations:
    oci.oraclecloud.com/load-balancer-type: "nlb"
    oci-network-load-balancer.oraclecloud.com/is-preserve-source: "false"
    oci-network-load-balancer.oraclecloud.com/node-label-selector: node-role.kubernetes.io/master!=true
    oci-network-load-balancer.oraclecloud.com/security-list-management-mode: "All"
  ports:
  - name: status-port
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
