{{- range $key, $val := $.Values.base64DockerConfigs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $key }}
  namespace: {{ $.Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $val }}
{{- end }}
