meshConfig:
  extensionProviders:
  - name: oauth2-proxy
    envoyExtAuthzHttp:
      service: oauth2-oauth2-proxy.infra.svc.cluster.local
      port: 80
      includeHeadersInCheck: ["authorization", "cookie"]
      headersToUpstreamOnAllow:
      - x-forwarded-access-token
      - authorization
      - path
      - x-auth-request-user
      - x-auth-request-email
      - x-auth-request-access-token
      headersToDownstreamOnDeny: ["content-type", "set-cookie"]
      includeAdditionalHeadersInCheck:
        X-Auth-Request-Redirect: 'https://%REQ(:authority)%%REQ(:path)%'
