apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Release.Name }}
spec:
  provider:
    oracle:
      vault: {{ .Values.oracle.vault.ocid }}
      region: {{ .Values.oracle.vault.region }}
      principalType: UserPrincipal
      auth:
        user: {{ .Values.oracle.vault.user }}
        tenancy: {{ .Values.oracle.vault.tenancy }}
        secretRef:
          privatekey:
            namespace: {{ .Release.Namespace }}
            name: {{ .Release.Name }}
            key: privateKey
          fingerprint:
            namespace: {{ .Release.Namespace }}
            name: {{ .Release.Name }}
            key: fingerprint
