applications:
- name: istio
  namespace: argocd
  project: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  destination:
    namespace: istio-system
    name: in-cluster 
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: base
    helm:
      releaseName: istio
      values: |
        service:
          type: None
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:                                                                                                                   
  - kind: ValidatingWebhookConfiguration
    group: admissionregistration.k8s.io  
    name: istiod-default-validator
    jqPathExpressions:                                                                                                                 
    - .webhooks[].failurePolicy
- name: istio-ingressgateway
  namespace: argocd
  project: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  destination:
    namespace: gateway
    name: in-cluster 
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    helm:
      releaseName: istio-ingressgateway
      parameters:
      - name: "service.annotations.oci-network-load-balancer\\.oraclecloud\\.com/oci-network-security-groups"
      values: |
        kind: DaemonSet
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-role
                  operator: In
                  values:
                  - "worker"
        service:
          externalTrafficPolicy: Local
          annotations:
            oci.oraclecloud.com/load-balancer-type: "nlb"
            oci-network-load-balancer.oraclecloud.com/is-preserve-source: "false"
            oci-network-load-balancer.oraclecloud.com/node-label-selector: node-role=worker
            oci-network-load-balancer.oraclecloud.com/security-list-management-mode: "All"
          ports:
          - name: status-port
            port: 15021
            protocol: TCP
            targetPort: 15021
          - name: https
            port: 443
            protocol: TCP
            targetPort: 443
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true
- name: cert-manager
  namespace: argocd
  project: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  destination:
    namespace: gateway
    name: in-cluster 
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true
- name: origin-ca-issuer-controller
  namespace: argocd
  project: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  destination:
    namespace: gateway
    name: in-cluster
  source:
    chart: origin-ca-issuer-controller
    helm:
      releaseName: origin-ca-issuer-controller
      values: |
        controller:
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 50Mi
        certmanager:
          namespace: gateway
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true
- name: origin-ca-issuer
  namespace: argocd
  project: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  destination:
    namespace: gateway
    name: in-cluster 
  source:
    chart: origin-ca-issuer
    helm:
      releaseName: origin-ca-issuer
      parameters:
      - name: "originCAissuerKey"
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true                                                                                               
- name: role-with-rolebinding
  namespace: argocd
  project: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  source:
    chart: role-with-rolebinding
    helm:
      releaseName: role-with-rolebinding
      values: |
        roles:
        - name: deploy-certificates
          namespace: gateway
          rules:
          - apiGroups: ["cert-manager.io"]
            resources: ["certificates"]
            verbs: ["get", "watch", "list", "patch", "create", "delete"]
        - name: deploy-gateways
          namespace: gateway
          rules:
          - apiGroups: ["networking.istio.io"]
            resources: ["gateways"]
            verbs: ["get", "watch", "list", "patch", "create", "delete"]
  destination:
    namespace: gateway
    name: in-cluster 
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true
- name: argocd-istio-gateway
  namespace: argocd
  project: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  destination:
    namespace: argocd
    name: in-cluster 
  source:
    chart: istio-gateway
    helm:
      releaseName: argocd-istio-gateway
      values: |
        hosts:
        - "argocd.from-the-lamp.work"
        external: true
        virtualService:
          destination:
            host: argo-cd-argocd-server
            port: 80
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: cert-manager.io
    kind: Certificate
    jsonPointers:
    - /spec/duration
    - /spec/renewBefore
    