projects:
  platform-preprod:
    namespace: argocd
    description: Platform apps Preprod
    sourceRepos:
    - '*'
    destinations:
    - name: in-cluster
      namespace: '*'
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  product-preprod:
    namespace: argocd
    description: Business apps Preprod 
    sourceRepos:
    - '*'
    destinations:
    - name: in-cluster
      namespace: product
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  platform-prod:
    namespace: argocd
    description: Platform apps Prod
    sourceRepos:
    - '*'
    destinations:
    - name: prod
      namespace: '*'
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  product-prod:
    namespace: argocd
    description: Business apps Prod 
    sourceRepos:
    - '*'
    destinations:
    - name: prod
      namespace: product
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
