projects:
  platform-infra:
    namespace: argocd
    description: Platform apps Infra
    sourceRepos:
    - '*'
    destinations:
    - name: infra
      namespace: '*'
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  platform-prod:
    namespace: argocd
    description: Platform apps Prod
    sourceRepos:
    - '*'
    destinations:
    - name: prod-0
      namespace: '*'
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  product-prod:
    namespace: argocd
    description: Business apps Prod 
    sourceRepos:
    - '*'
    destinations:
    - name: prod-0
      namespace: product
    - name: prod-0
      namespace: istio-system
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
