applications:
- name: general
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  destination:
    name: in-cluster
  sources:
  - chart: base
    helm:
      releaseName: general
      valueFiles:
      - $values/values.prod.yml
      parameters:
      - name: image.name
        value: registry.gitlab.com/from-the-lamp/frontend/general
      - name: image.tag
        value: latest
  - ref: values
    repoURL: https://gitlab.com/from-the-lamp/frontend/general.git
    targetRevision: main
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true
  ignoreDifferences:
  - group: cert-manager.io
    kind: Certificate
    jsonPointers:
    - /spec/duration
    - /spec/renewBefore
- name: book
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  destination:
    name: in-cluster
  sources:
  - chart: base
    helm:
      releaseName: book
      valueFiles:
      - $values/values.prod.yml
      parameters:
      - name: image.name
        value: registry.gitlab.com/from-the-lamp/frontend/book
      - name: image.tag
        value: latest
  - ref: values
    repoURL: https://gitlab.com/from-the-lamp/frontend/book.git
    targetRevision: main
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true
  ignoreDifferences:
  - group: cert-manager.io
    kind: Certificate
    jsonPointers:
    - /spec/duration
    - /spec/renewBefore
